### ISSUE TITLE
On mobile, meetUs cards should be displayed as one column

### ISSUE THREAD

**Issue by Macryo** [Macryo/Equarium#15]

**Comment by mecies** [comment]
Hmm this issue is strange because according to the mobile media query in meetus grid section there ought to be only one column, please do double-check. 💃

**Comment by Macryo** [comment]
Solution found: chrome requires meta tag 	
`<meta name="viewport" content="width=device-width, initial-scale=1.0">`

**Comment by mecies** [comment]
Fixed with the tag !
