### ISSUE TITLE
Unify page navigation buttons in: Mentorzy, O projekci. Studenci

### ISSUE THREAD

**Issue by Macryo** [Macryo/Equarium#31]
![image](https://user-images.githubusercontent.com/16615258/55322678-45311300-547d-11e9-905e-7296f607d37a.png)

This is actual look, and bellow is desired one(like in Kontakt xd, po co ja piszę po angielsku?):

![image](https://user-images.githubusercontent.com/16615258/55322709-5bd76a00-547d-11e9-85a0-f3c27f8c7e94.png)

**Comment by M0arcin** [comment]
Solved in the newest commit on develop refactor
