### ISSUE TITLE
Sekcja co u nas słychać - przygotowanie slidera

### ISSUE THREAD

**Issue by Macryo** [Macryo/Equarium#5]
Sekcja co u nas słychać - zrobienie slidera ze wszystkimi wiadomościami(najlepiej w formie template). Slider **musi** być responsywny.

**Comment by mecies** [comment]
Zostało mi dodanie zmiany tła na strzałkach po bokach i na ten moment nie mam pomysłu jak się za to zabrać, z jakiegoś powodu nie mogę porównywać element.style.backgroundImage
